
-- ----------------------------
-- Table structure for XXL_JOB_GROUP
-- ----------------------------

CREATE TABLE "XXL_JOB_GROUP" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "APP_NAME" NVARCHAR2(64) VISIBLE NOT NULL,
  "TITLE" NVARCHAR2(12) VISIBLE NOT NULL,
  "ADDRESS_TYPE" NUMBER(4,0) VISIBLE NOT NULL,
  "ADDRESS_LIST" NVARCHAR2(512) VISIBLE
)

;
COMMENT ON COLUMN "XXL_JOB_GROUP"."APP_NAME" IS '执行器AppName';
COMMENT ON COLUMN "XXL_JOB_GROUP"."TITLE" IS '执行器名称';
COMMENT ON COLUMN "XXL_JOB_GROUP"."ADDRESS_TYPE" IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN "XXL_JOB_GROUP"."ADDRESS_LIST" IS '执行器地址列表，多地址逗号分隔';

-- ----------------------------
-- Table structure for XXL_JOB_INFO
-- ----------------------------

CREATE TABLE "XXL_JOB_INFO" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "JOB_GROUP" NUMBER(11,0) VISIBLE NOT NULL,
  "JOB_CRON" NVARCHAR2(128) VISIBLE NOT NULL,
  "JOB_DESC" NVARCHAR2(255) VISIBLE NOT NULL,
  "ADD_TIME" DATE VISIBLE,
  "UPDATE_TIME" DATE VISIBLE,
  "AUTHOR" NVARCHAR2(64) VISIBLE,
  "ALARM_EMAIL" NVARCHAR2(255) VISIBLE,
  "EXECUTOR_ROUTE_STRATEGY" NVARCHAR2(50) VISIBLE,
  "EXECUTOR_HANDLER" NVARCHAR2(255) VISIBLE,
  "EXECUTOR_PARAM" NVARCHAR2(512) VISIBLE,
  "EXECUTOR_BLOCK_STRATEGY" NVARCHAR2(50) VISIBLE,
  "EXECUTOR_TIMEOUT" NUMBER(11,0) VISIBLE NOT NULL,
  "EXECUTOR_FAIL_RETRY_COUNT" NUMBER(11,0) VISIBLE NOT NULL,
  "GLUE_TYPE" NVARCHAR2(50) VISIBLE NOT NULL,
  "GLUE_SOURCE" NCLOB VISIBLE,
  "GLUE_REMARK" NVARCHAR2(128) VISIBLE,
  "GLUE_UPDATETIME" DATE VISIBLE,
  "CHILD_JOBID" NVARCHAR2(255) VISIBLE,
  "TRIGGER_STATUS" NUMBER(4,0) VISIBLE NOT NULL,
  "TRIGGER_LAST_TIME" NUMBER(20,0) VISIBLE NOT NULL,
  "TRIGGER_NEXT_TIME" NUMBER(20,0) VISIBLE NOT NULL
)

;
COMMENT ON COLUMN "XXL_JOB_INFO"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "XXL_JOB_INFO"."JOB_CRON" IS '任务执行CRON';
COMMENT ON COLUMN "XXL_JOB_INFO"."AUTHOR" IS '作者';
COMMENT ON COLUMN "XXL_JOB_INFO"."ALARM_EMAIL" IS '报警邮件';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_ROUTE_STRATEGY" IS '执行器路由策略';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_BLOCK_STRATEGY" IS '阻塞处理策略';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_TIMEOUT" IS '任务执行超时时间，单位秒';
COMMENT ON COLUMN "XXL_JOB_INFO"."EXECUTOR_FAIL_RETRY_COUNT" IS '失败重试次数';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_REMARK" IS 'GLUE备注';
COMMENT ON COLUMN "XXL_JOB_INFO"."GLUE_UPDATETIME" IS 'GLUE更新时间';
COMMENT ON COLUMN "XXL_JOB_INFO"."CHILD_JOBID" IS '子任务ID，多个逗号分隔';
COMMENT ON COLUMN "XXL_JOB_INFO"."TRIGGER_STATUS" IS '调度状态：0-停止，1-运行';
COMMENT ON COLUMN "XXL_JOB_INFO"."TRIGGER_LAST_TIME" IS '上次调度时间';
COMMENT ON COLUMN "XXL_JOB_INFO"."TRIGGER_NEXT_TIME" IS '下次调度时间';

-- ----------------------------
-- Table structure for XXL_JOB_LOCK
-- ----------------------------

CREATE TABLE "XXL_JOB_LOCK" (
  "LOCK_NAME" NVARCHAR2(50) VISIBLE NOT NULL
)

;
COMMENT ON COLUMN "XXL_JOB_LOCK"."LOCK_NAME" IS '锁名称';

-- ----------------------------
-- Table structure for XXL_JOB_LOG
-- ----------------------------

CREATE TABLE "XXL_JOB_LOG" (
  "ID" NUMBER(20,0) VISIBLE NOT NULL,
  "JOB_GROUP" NUMBER(11,0) VISIBLE NOT NULL,
  "JOB_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "EXECUTOR_ADDRESS" NVARCHAR2(255) VISIBLE,
  "EXECUTOR_HANDLER" NVARCHAR2(255) VISIBLE,
  "EXECUTOR_PARAM" NVARCHAR2(512) VISIBLE,
  "EXECUTOR_SHARDING_PARAM" NVARCHAR2(20) VISIBLE,
  "EXECUTOR_FAIL_RETRY_COUNT" NUMBER(11,0) VISIBLE DEFAULT 0 NOT NULL,
  "TRIGGER_TIME" DATE VISIBLE,
  "TRIGGER_CODE" NUMBER(11,0) VISIBLE NOT NULL,
  "TRIGGER_MSG" NCLOB VISIBLE,
  "HANDLE_TIME" DATE VISIBLE,
  "HANDLE_CODE" NUMBER(11,0) VISIBLE NOT NULL,
  "HANDLE_MSG" NCLOB VISIBLE,
  "ALARM_STATUS" NUMBER(4,0) VISIBLE DEFAULT 0 NOT NULL
)

;
COMMENT ON COLUMN "XXL_JOB_LOG"."JOB_GROUP" IS '执行器主键ID';
COMMENT ON COLUMN "XXL_JOB_LOG"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_ADDRESS" IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_HANDLER" IS '执行器任务handler';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_PARAM" IS '执行器任务参数';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_SHARDING_PARAM" IS '执行器任务分片参数，格式如 1/2';
COMMENT ON COLUMN "XXL_JOB_LOG"."EXECUTOR_FAIL_RETRY_COUNT" IS '失败重试次数';
COMMENT ON COLUMN "XXL_JOB_LOG"."TRIGGER_TIME" IS '调度-时间';
COMMENT ON COLUMN "XXL_JOB_LOG"."TRIGGER_CODE" IS '调度-结果';
COMMENT ON COLUMN "XXL_JOB_LOG"."TRIGGER_MSG" IS '调度-日志';
COMMENT ON COLUMN "XXL_JOB_LOG"."HANDLE_TIME" IS '执行-时间';
COMMENT ON COLUMN "XXL_JOB_LOG"."HANDLE_CODE" IS '执行-状态';
COMMENT ON COLUMN "XXL_JOB_LOG"."HANDLE_MSG" IS '执行-日志';
COMMENT ON COLUMN "XXL_JOB_LOG"."ALARM_STATUS" IS '告警状态：0-默认、1-无需告警、2-告警成功、3-告警失败';

-- ----------------------------
-- Table structure for XXL_JOB_LOG_REPORT
-- ----------------------------

CREATE TABLE "XXL_JOB_LOG_REPORT" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "TRIGGER_DAY" DATE VISIBLE,
  "RUNNING_COUNT" NUMBER(11,0) VISIBLE NOT NULL,
  "SUC_COUNT" NUMBER(11,0) VISIBLE NOT NULL,
  "FAIL_COUNT" NUMBER(11,0) VISIBLE NOT NULL
)

;
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."TRIGGER_DAY" IS '调度-时间';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."RUNNING_COUNT" IS '运行中-日志数量';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."SUC_COUNT" IS '执行成功-日志数量';
COMMENT ON COLUMN "XXL_JOB_LOG_REPORT"."FAIL_COUNT" IS '执行失败-日志数量';

-- ----------------------------
-- Table structure for XXL_JOB_LOGGLUE
-- ----------------------------

CREATE TABLE "XXL_JOB_LOGGLUE" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "JOB_ID" NUMBER(11,0) VISIBLE NOT NULL,
  "GLUE_TYPE" NVARCHAR2(50) VISIBLE,
  "GLUE_SOURCE" NCLOB VISIBLE,
  "GLUE_REMARK" NVARCHAR2(128) VISIBLE NOT NULL,
  "ADD_TIME" DATE VISIBLE,
  "UPDATE_TIME" DATE VISIBLE
)
TABLESPACE "INSIGHT"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."JOB_ID" IS '任务，主键ID';
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."GLUE_TYPE" IS 'GLUE类型';
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."GLUE_SOURCE" IS 'GLUE源代码';
COMMENT ON COLUMN "XXL_JOB_LOGGLUE"."GLUE_REMARK" IS 'GLUE备注';

-- ----------------------------
-- Table structure for XXL_JOB_REGISTRY
-- ----------------------------

CREATE TABLE "XXL_JOB_REGISTRY" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "REGISTRY_GROUP" NVARCHAR2(50) VISIBLE NOT NULL,
  "REGISTRY_KEY" NVARCHAR2(255) VISIBLE NOT NULL,
  "REGISTRY_VALUE" NVARCHAR2(255) VISIBLE NOT NULL,
  "UPDATE_TIME" DATE VISIBLE
)

;

-- ----------------------------
-- Table structure for XXL_JOB_USER
-- ----------------------------

CREATE TABLE "XXL_JOB_USER" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "USERNAME" NVARCHAR2(50) VISIBLE NOT NULL,
  "PASSWORD" NVARCHAR2(50) VISIBLE NOT NULL,
  "ROLE" NUMBER(4,0) VISIBLE NOT NULL,
  "PERMISSION" NVARCHAR2(255) VISIBLE
)

;
COMMENT ON COLUMN "XXL_JOB_USER"."USERNAME" IS '账号';
COMMENT ON COLUMN "XXL_JOB_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "XXL_JOB_USER"."ROLE" IS '角色：0-普通用户、1-管理员';
COMMENT ON COLUMN "XXL_JOB_USER"."PERMISSION" IS '权限：执行器ID列表，多个逗号分割';

-- ----------------------------
-- Primary Key structure for table XXL_JOB_GROUP
-- ----------------------------
ALTER TABLE "XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C0021912" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_GROUP
-- ----------------------------
ALTER TABLE "XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C0021875" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C0021876" CHECK ("APP_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C0021877" CHECK ("TITLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_GROUP" ADD CONSTRAINT "SYS_C0021878" CHECK ("ADDRESS_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_INFO
-- ----------------------------
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0021917" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_INFO
-- ----------------------------
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0021879" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0021880" CHECK ("JOB_GROUP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0021881" CHECK ("JOB_CRON" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0021882" CHECK ("JOB_DESC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0021883" CHECK ("EXECUTOR_TIMEOUT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0021884" CHECK ("EXECUTOR_FAIL_RETRY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0021885" CHECK ("GLUE_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0021886" CHECK ("TRIGGER_STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0021887" CHECK ("TRIGGER_LAST_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_INFO" ADD CONSTRAINT "SYS_C0021888" CHECK ("TRIGGER_NEXT_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_LOCK
-- ----------------------------
ALTER TABLE "XXL_JOB_LOCK" ADD CONSTRAINT "SYS_C0021911" PRIMARY KEY ("LOCK_NAME");

-- ----------------------------
-- Checks structure for table XXL_JOB_LOCK
-- ----------------------------
ALTER TABLE "XXL_JOB_LOCK" ADD CONSTRAINT "SYS_C0021874" CHECK ("LOCK_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_LOG
-- ----------------------------
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0021914" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_LOG
-- ----------------------------
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0021889" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0021890" CHECK ("JOB_GROUP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0021891" CHECK ("JOB_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0021892" CHECK ("EXECUTOR_FAIL_RETRY_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0021893" CHECK ("TRIGGER_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0021894" CHECK ("HANDLE_CODE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG" ADD CONSTRAINT "SYS_C0021895" CHECK ("ALARM_STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table XXL_JOB_LOG
-- ----------------------------
CREATE INDEX "I_handle_code"
  ON "XXL_JOB_LOG" ("HANDLE_CODE" ASC)
;
CREATE INDEX "I_trigger_time"
  ON "XXL_JOB_LOG" ("TRIGGER_TIME" ASC)
;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_LOG_REPORT
-- ----------------------------
ALTER TABLE "XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C0021915" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_LOG_REPORT
-- ----------------------------
ALTER TABLE "XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C0021896" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C0021897" CHECK ("RUNNING_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C0021898" CHECK ("SUC_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOG_REPORT" ADD CONSTRAINT "SYS_C0021899" CHECK ("FAIL_COUNT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table XXL_JOB_LOG_REPORT
-- ----------------------------
CREATE UNIQUE INDEX "i_trigger_day"
  ON "XXL_JOB_LOG_REPORT" ("TRIGGER_DAY" ASC)
;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_LOGGLUE
-- ----------------------------
ALTER TABLE "XXL_JOB_LOGGLUE" ADD CONSTRAINT "SYS_C0021913" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_LOGGLUE
-- ----------------------------
ALTER TABLE "XXL_JOB_LOGGLUE" ADD CONSTRAINT "SYS_C0021900" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOGGLUE" ADD CONSTRAINT "SYS_C0021901" CHECK ("JOB_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_LOGGLUE" ADD CONSTRAINT "SYS_C0021902" CHECK ("GLUE_REMARK" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_REGISTRY
-- ----------------------------
ALTER TABLE "XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C0021918" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_REGISTRY
-- ----------------------------
ALTER TABLE "XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C0021903" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C0021904" CHECK ("REGISTRY_GROUP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C0021905" CHECK ("REGISTRY_KEY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_REGISTRY" ADD CONSTRAINT "SYS_C0021906" CHECK ("REGISTRY_VALUE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table XXL_JOB_REGISTRY
-- ----------------------------
CREATE INDEX "i_g_k_v"
  ON "XXL_JOB_REGISTRY" ("REGISTRY_GROUP" ASC, "REGISTRY_VALUE" ASC, "REGISTRY_KEY" ASC)
;

-- ----------------------------
-- Primary Key structure for table XXL_JOB_USER
-- ----------------------------
ALTER TABLE "XXL_JOB_USER" ADD CONSTRAINT "SYS_C0021916" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table XXL_JOB_USER
-- ----------------------------
ALTER TABLE "XXL_JOB_USER" ADD CONSTRAINT "SYS_C0021907" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_USER" ADD CONSTRAINT "SYS_C0021908" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_USER" ADD CONSTRAINT "SYS_C0021909" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "XXL_JOB_USER" ADD CONSTRAINT "SYS_C0021910" CHECK ("ROLE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table XXL_JOB_USER
-- ----------------------------
CREATE UNIQUE INDEX "i_username"
  ON "XXL_JOB_USER" ("USERNAME" ASC)
;

INSERT INTO "XXL_JOB_GROUP"("ID", "APP_NAME", "TITLE", "ADDRESS_TYPE", "ADDRESS_LIST") VALUES ('1', 'xxl-job-executor-sample', '示例执行器', '0', NULL);
INSERT INTO "XXL_JOB_LOCK"("LOCK_NAME") VALUES ('schedule_lock');
INSERT INTO "XXL_JOB_INFO"("ID", "JOB_GROUP", "JOB_CRON", "JOB_DESC", "ADD_TIME", "UPDATE_TIME", "AUTHOR", "ALARM_EMAIL", "EXECUTOR_ROUTE_STRATEGY", "EXECUTOR_HANDLER", "EXECUTOR_PARAM", "EXECUTOR_BLOCK_STRATEGY", "EXECUTOR_TIMEOUT", "EXECUTOR_FAIL_RETRY_COUNT", "GLUE_TYPE", "GLUE_SOURCE", "GLUE_REMARK", "GLUE_UPDATETIME", "CHILD_JOBID", "TRIGGER_STATUS", "TRIGGER_LAST_TIME", "TRIGGER_NEXT_TIME") VALUES ('1', '1', '* * * * * ?', '测试任务1', TO_DATE('2018-11-03 22:21:31', 'SYYYY-MM-DD HH24:MI:SS'), TO_DATE('2020-06-19 12:27:18', 'SYYYY-MM-DD HH24:MI:SS'), 'XXL', NULL, 'FIRST', 'demoJobHandler', NULL, 'SERIAL_EXECUTION', '0', '0', 'BEAN', NULL, 'GLUE代码初始化', TO_DATE('2018-11-03 22:21:31', 'SYYYY-MM-DD HH24:MI:SS'), NULL, '0', '0', '0');
INSERT INTO "XXL_JOB_USER"("ID", "USERNAME", "PASSWORD", "ROLE", "PERMISSION") VALUES ('1', 'admin', 'e10adc3949ba59abbe56e057f20f883e', '1', NULL);

-- Create sequence
create sequence XXL_JOB_GROUP_ID
minvalue 1
maxvalue 999999999999
start with 2
increment by 1
cache 20
cycle;

-- Create sequence
create sequence XXL_JOB_INFO_ID
minvalue 1
maxvalue 999999999999
start with 2
increment by 1
cache 20
cycle;

-- Create sequence
create sequence XXL_JOB_LOGGLUE_ID
minvalue 1
maxvalue 999999999999
start with 1
increment by 1
cache 20
cycle;

-- Create sequence
create sequence XXL_JOB_LOG_ID
minvalue 1
maxvalue 999999999999
start with 1
increment by 1
cache 20
cycle;

-- Create sequence
create sequence XXL_JOB_REGISTRY_ID
minvalue 1
maxvalue 999999999999
start with 1
increment by 1
cache 20
cycle;

-- Create sequence
create sequence XXL_JOB_USER_ID
minvalue 1
maxvalue 999999999999
start with 2
increment by 1
cache 20
cycle;

-- Create sequence
create sequence XXL_JOB_LOG_REPORT_ID
minvalue 1
maxvalue 999999999999
start with 2
increment by 1
cache 20
cycle;